### ISSUE TITLE
Code block detection seems somewhat broken

### ISSUE THREAD

**Issue by xolox** [xolox/vim-notes#102]
Issues #79 and #83 reported that text substitution and note highlighting should not happen inside code blocks, this was fixed in a6a654f. Pull request #98 (merged in 6f4ad2b4d8a58c2a55c8d17f8439c63b24e2a684) introduced GFM style fenced code blocks and I tried to fit this in with the changes in a6a654f but apparently that didn't work out very well because I've started noticing that the feature introduced in a6a654f is broken when e.g. between two code blocks.

One very blunt option is to exclude GFM style fenced code blocks from the feature introduced in a6a654f. The better option is of course to get this working for both styles of code blocks. The problem with that is that the start/end markers of GFM style fenced code blocks are the same... (in other words, I picked the original style of code blocks with a very good reason :-)

**Comment by gstewart** [comment]
I was seeing this problem with bullets,etc. and folding of headings not working after the code blocks. 

I did some experimenting and see the problem with 6f4ad2b (or atleast what is causing the issues for me). 

In the function ```xolox#notes#inside_snippet```, the line:

```viml
return search('{{{\|\(}}}\)', 'bnpW') == 1
```

was replaced with this to handle the GFM style code blocks:

```viml
let matching_subpattern = search('{{{\|\(}}}\)\|```\w\|\(```\)', 'bnpW')
return matching_subpattern >= 1
```

Looking at the docs for ```search()```, I think you'd still want to do ```return matching_subpattern == 1```
```
With the 'p' flag the returned value is one more than the
first sub-match in \(\).  One if none of them matched but the
whole pattern did match.
```

When I test it out I get the following from ```search()```:

* When after a ```{{{...}}}``` block, it returns **2** (sub-match 1 + 1)
* When after a GFM style block, it returns **3** (sub-match 2 + 1)
* When inside a ```{{{...}}}``` or GFM style block, it returns **1** (matched whole pattern but no sub-match)
* When before any code blocks, it returns **0**

**Comment by xolox** [comment]
Thanks for the analysis @gstewart! I guess I was confused when I changed this during the merging of that pull request because your analysis looks correct - I tested and get the correct behavior even in fairly complex notes. I will close this issue now because it looks like the problem has been resolved.
