### ISSUE TITLE
Folding in vim-notes?

### ISSUE THREAD

**Issue by rfegq4** [xolox/vim-notes#106]
Does vim-notes support header and bullet-list folding?

**Comment by xolox** [comment]
You could have just tried ;-). However thanks for pointing out a weak spot in the documentation.

I've now documented text folding of headers in the readme and included a screenshot in the repository (linked from the readme, also shown below).

Bullet list folding is not supported and to be honest I don't see how that would fit into the current feature set, e.g. how would/should it combine with the existing text folding of headers?

Does this answer your question? If so then please close this issue. Thanks for the feedback!

----

![Text folding of headers in vim-notes](https://raw.githubusercontent.com/xolox/vim-notes/master/screenshots/folding.png)

**Comment by Jeel-Shah** [comment]
Is there a shortcut to fold heading/subheading?

**Comment by lkwd-daved** [comment]
I would like this also

**Comment by umnikos** [comment]
For anyone else viewing this on a later date, the vim shortcut for folding headers is `za`. :+1:
