### ISSUE TITLE
No matching autocommands

### ISSUE THREAD

**Issue by xHN35RQ** [xolox/vim-notes#109]
For some reason on each `:wq` Vim tells me `No matching autocommands` and I've been able to isolate the issue to vim-notes. I'm thinking there's an autocommand somewhere that is not silent?

**Comment by xHN35RQ** [comment]
Closing because this is no longer an issue.

**Comment by jnor** [comment]
I have the same issue, only when I type **:w** though, not when I do **:wq**

**Comment by qinfuqi** [comment]
how is it closed. I still got the itchy issue. someone help?
