### ISSUE TITLE
Is there any way I can see list of all my notes ?

### ISSUE THREAD

**Issue by collegeimprovements** [xolox/vim-notes#118]
I would like to see the list of all notes! 
As tab-completion suggests way more options which are not actually my notes.
It would be great to be able to search all my notes.

**Comment by xolox** [comment]
To search through your notes you can use the `:SearchNotes` command. The `:ShowTaggedNotes` command gives an overview of all notes. It's meant to be used with tags but it also shows untagged notes, effectively listing the names of all your notes. Does this help?

**Comment by aliawa** [comment]
:ShowTaggedNotes works only if you have at least one tag somewhere in your notes. If you have never tagged anything this does not work.

**Comment by lkraav** [comment]
I'm also somewhat confused by omission of a `:BrowseNotes` command. In the meanwhile, `:RecentNotes` is helpful. Perhaps without the date restriction, this command could be aliased to `:BrowseNotes`.
