### ISSUE TITLE
Line wrap when writing bullet points

### ISSUE THREAD

**Issue by krishnavaidy** [xolox/vim-notes#132]
When typing in bulleted list, vim automatically wraps line after 80 characters. But in vim-notes, after 80 characters  a new bullet list appears automatically when line is wrapped. Tried :set nowrap, but this behaviour still persists.

Please let me know if I missed a part  of the README, or FAQ!

Thanks!
Krishna.

**Comment by epatpol** [comment]
Just installed vim-notes and I do not have this problem. I can't seem to reproduce it. Maybe you have some options/plug-ins that are changing the expected behavior. Care to share your .vimrc?

**Comment by krishnavaidy** [comment]
Oh! That's strange. My vimrc is [here](https://gist.github.com/krishnavaidy/6e0dd3d6aa3541deff7982c92ba4e381) . I am not sure if some of my addons is causing this.

Thanks for taking a look at this!

**Comment by epatpol** [comment]
Wait a minute, I noticed that my bullet point wrapping never worked for me, so when I used your settings to wrap a line at 80 characters, it didn't create a new bullet point. I was indeed able to reproduce your bug when using the default Note template and going to the end of the line. That is weird.

**Comment by krishnavaidy** [comment]
Do you happen to use a different Note template, which avoids this bug?

Thanks!

**Comment by epatpol** [comment]
No, not that I'm aware of... Well the problem must be in my vimrc, as I simply cannot use the bullet point wrapping when creating new notes... Pressing enter at the end of a bullet point creates a new line, but it does not create a new bullet point. I should investigate with that. Here's my vimrc if you're interested https://raw.githubusercontent.com/patoupatou/dotfiles/master/vim/.vimrc

**Comment by krishnavaidy** [comment]
Many thanks for the link to your vimrc! I really appreciate you investigating this. I'll also take a look at the code next week, to figure what's going on. I love vim, and think you guys are doing a great job with vim-notes. Please let me know if you'd like any help with this from me.

**Comment by krishnavaidy** [comment]
I noticed that this error is replicating when not in vim-notes. When you try to type in a normal txt file with a \* bullet point and exceed the textwidth, it automatically goes to the next line with a new *. Should this be raised in the vim github page?

**Comment by epatpol** [comment]
Good point @krishnavaidy, well to be honest I still don't know why bullet point wrapping doesn't work for me... But it is kinda annoying having to type \* when pressing enter for a bullet point AFTER a bullet point. I don't think it's a vim bug, but probably configuration... Feel free to update the thread if you end up making it work!

Thanks

**Comment by krishnavaidy** [comment]
I also feel that this is a configuration issue, so I'll close this issue. I was seeing the plugin vim-markdown and I saw that it had a configuration to disable folding for md files. I feel like something similar needs to be done for vim-notes. I'll update this thread when I find a workaround for this.

Thanks for taking a look at this!
