### ISSUE TITLE
Strikethrough text?

### ISSUE THREAD

**Issue by AnatoleLucet** [xolox/vim-notes#183]
I'm not sure if this is possible, but It'd be nice to have strikethrough text in notes.

For example I like to use strikethrough in lists :

- ~~something done~~
- something to do

```
- ~~something done~~
- something to do
```

**Comment by AnatoleLucet** [comment]
ok my bad, this isn't maintained anymore

**Comment by brotherJ4mes** [comment]
I realize this is pretty old but I forked vim-notes in order to enable strikethrough highlighting.

https://github.com/brotherJ4mes/vim-notes

(Despite the lack of maintenance I still find that vim-notes works great)
