### ISSUE TITLE
Feature request: config option to replace spaces in filenames

### ISSUE THREAD

**Issue by bryankennedy** [xolox/vim-notes#52]
I'm playing around with Vim-Notes and love how it just handles the filename creation for you based on the first line of your file. However, this creates a bunch of files with spaces in them. These are difficult to open with the :SearchNotes command, because Vim doesn't recognize the space in the filename when trying to use the gf command.

Would it be possible to add a configuration option where users could replace all spaces in their note filenames with a specific character such as a dash or underscore?

If I'm going about this SearchNotes functionality in some wrong way, please let me know.

**Comment by xolox** [comment]
I'm going to close this issue due to lack of feedback. If you can provide more information feel free to reopen this issue.
