### ISSUE TITLE
FR : Recursive Search?

### ISSUE THREAD

**Issue by blurmonk** [xolox/vim-notes#71]
Hi

I tried recursive searching(I have notes in sub folders). it does not seem to find anything in the folders. Does it support subfolders?

thanks

**Comment by xolox** [comment]
I'm going to close this issue now because the feature request has been implemented and there were no complaints about the functionality (I'm referring to the recursive search, not #82). Thanks for the feedback and happy Vimming!

**Comment by jsit** [comment]
Is it possible to make this into an option? For instance I'd like to keep my vim-notes metadata as a subdir in my notes directory, and recursive scanning means that my tags.txt file shows up in `:SearchNotes`.
