### ISSUE TITLE
almost none of the key mappings work. documentation doesn't work.

### ISSUE THREAD

**Issue by zee0** [xolox/vim-notes#81]
i'm a bit confused as to why this doesn't work fully on my system. installed both the notes and misc packages. gvim on ubuntu.

opening a new note works fine, but then only half the syntaxes work. even going down to "Note taking syntax" and hitting 'gf' as directed in the opening instructions only gives an error "Can't find file "Note" in path."

```
DONE, TODO, XXX work.
# header works.
*bold* works.
_italic_ works.
file paths work.

lists do not work. [tab, *, +, -]
*** does not enter a page break.
urls are not shortened [http://]
smart quotes "" '' do not work.
-- doesn't work.
-> and <- don't work.
```

![screenshot from 2014-08-26 12 46 04](https://cloud.githubusercontent.com/assets/7860857/4048109/7fd91430-2d40-11e4-82bf-7df445cdc9db.png)

**Comment by xolox** [comment]
I'm going to close this issue due to lack of feedback (for quite a few months now). If anyone feels up to it, feel free to reopen this issue with more information.

**Comment by eb0t** [comment]
filetype plugin on   
put that command in your .vimrc
