### ISSUE TITLE
bash code block changes filetype, breaks save

### ISSUE THREAD

**Issue by jagipson** [xolox/vim-notes#87]
I have an issue using vim 7.4 on Linux. When I use the syntax code block structure {{{ with bash.

When I have a code block like this:
```
{{{bash
some commands
}}}
```

The syntax highlighting seems to work _inside_ the `{{{...}}}`, but the `{{{bash` and `}}}` remain visible (dark gray).  I discovered that the buffer's `filetype` is set to `sh` and that breaks saving the buffer as the save function requires the`filetype` be `notes`.

I have confirmed that using `{{{sh` and also `{{{invalid` *don't* have this effect. It's something special about the `bash` file type.

If this can't be fixed, I'd recommend adding an `else` to the `if xolox#notes#filetype_is_note(&ft)` statement in the `xolox#notes#save()` function that prints an error message and ask the user to manually check/set the filetype and retry saving.

**Comment by xolox** [comment]
I'm going to close this issue due to lack of feedback, feel free to reopen the issue if you have more information.
