### ISSUE TITLE
Very slow editing with moderate size text file

### ISSUE THREAD

**Issue by gerroon** [xolox/vim-notes#92]
I cant edit any text that has anything longer than couple hundred words. The editing gets very slow. This gets even slower when wrapping is enabled.

If I change the type to =text the editing 10x faster (which is abit more bearable) 

I am guessing that this plugin sets the file as note type and does somework, however I am very much interested in increasing my editing speed.

thanks

**Comment by xolox** [comment]
Closing due to lack of feedback, feel free to reopen if you're interested in replying to my question.
